export type NewsItem = {
  slug: string
  category: string
  headline: string
  summary: string
  body: string[]
  source: string
  sourceUrl: string
  readTime: string
  featured: boolean
}

export const news: NewsItem[] = [
  {
    slug: 'anthropic-claude-enterprise-agentic-workflows',
    category: 'AI & Machine Learning',
    headline: 'Anthropic Expands Claude for Enterprise with Native Agentic Workflow Support',
    summary: 'Claude can now autonomously execute multi-step business workflows inside enterprise systems, marking a shift from AI assistant to AI operator.',
    body: [
      'Anthropic has released a major update to its enterprise Claude offering, adding native support for agentic workflows that allow the model to autonomously plan and execute multi-step tasks across connected business systems without human intervention at each step.',
      'The update introduces tool-use chains that enable Claude to read from databases, write to CRM platforms, trigger automation sequences, and validate its own outputs before surfacing results to end users. For enterprise customers, this means AI can now operate as an autonomous business process layer rather than a conversational assistant.',
      'Early deployments cited by Anthropic include automated contract review and data extraction pipelines, customer support ticket triage and resolution workflows, and financial report generation from live data sources. In all cases, Claude operates within a defined permission boundary set by the enterprise, with full audit trails for compliance purposes.',
      'The enterprise agentic capability is available through the Claude API and integrates with major enterprise platforms including Salesforce, ServiceNow, and Microsoft 365. Anthropic has also announced partnerships with leading automation vendors to offer pre-built workflow templates for common enterprise use cases.',
      'For businesses evaluating AI infrastructure, this development signals a meaningful acceleration in what AI can own end-to-end. The distinction between automation and AI is collapsing: the most sophisticated deployments will combine structured workflow logic with adaptive AI reasoning to handle exceptions that rule-based systems cannot.',
    ],
    source: 'Anthropic Blog',
    sourceUrl: 'https://www.anthropic.com/news',
    readTime: '4 min read',
    featured: true,
  },
  {
    slug: 'openai-o3-reasoning-business-automation',
    category: 'AI & Machine Learning',
    headline: 'OpenAI o3 Reasoning Model Now Available for Business Automation Use Cases',
    summary: 'The o3 model brings advanced multi-step reasoning to production automation pipelines, dramatically improving accuracy on complex decision-making tasks.',
    body: [
      'OpenAI has made its o3 reasoning model generally available through the API, opening access to its most capable reasoning system for enterprise and production automation use cases. The release marks a significant step in bringing advanced AI reasoning into real business workflows beyond research and experimentation.',
      'The o3 model excels at tasks requiring multi-step logical reasoning, complex data interpretation, and nuanced decision-making where simple pattern matching falls short. Early benchmarks show substantial improvements over previous models on tasks such as financial analysis, legal document review, compliance checking, and multi-variable operational decisions.',
      'For automation practitioners, the practical significance is that tasks previously requiring human expert review — due to complexity rather than sensitivity — can now be delegated to AI with confidence. This expands the scope of what automation can own, moving up the value chain from routine data processing to substantive analytical work.',
      'OpenAI has introduced a tiered pricing structure for o3 that balances cost against reasoning depth, allowing developers to choose between a standard tier for most automation tasks and an extended reasoning tier for the highest-complexity decisions. Both tiers are accessible through the existing API contract without renegotiation.',
      'The broader implication for enterprise technology strategy is that the capability gap between AI and human expert judgment continues to close on structured analytical tasks. Organisations building AI-augmented workflows now should design for progressive AI ownership as model capability increases rather than building fixed human-in-the-loop checkpoints that may become unnecessary.',
    ],
    source: 'OpenAI Blog',
    sourceUrl: 'https://openai.com/blog',
    readTime: '5 min read',
    featured: false,
  },
  {
    slug: 'microsoft-copilot-studio-autonomous-agents-ga',
    category: 'Business Automation',
    headline: 'Microsoft Copilot Studio Autonomous Agents Reach General Availability Across Microsoft 365',
    summary: 'Microsoft\'s autonomous AI agents can now independently handle end-to-end business processes inside Teams, Outlook, SharePoint, and Dynamics 365.',
    body: [
      'Microsoft has announced the general availability of Autonomous Agents in Copilot Studio, its enterprise AI development platform, bringing self-directed AI agents into the core Microsoft 365 ecosystem for the first time at production scale.',
      'The agents can be configured to monitor business triggers, make decisions, and take actions across Microsoft 365 services without human initiation at each step. Use cases in GA include: automated invoice routing and approval in Dynamics 365, customer inquiry resolution directly in Teams, document drafting and review workflows in SharePoint, and meeting follow-up action tracking in Outlook.',
      'Unlike traditional robotic process automation which follows fixed rule sequences, Copilot Studio agents use natural language reasoning to interpret context and adapt their actions based on the specific situation. An agent handling a supplier invoice, for example, can identify discrepancies, query the relevant contact, and escalate appropriately without being explicitly programmed for every edge case.',
      'For IT and operations leaders already invested in the Microsoft ecosystem, the significance of this release is considerable. The barrier to deploying production-grade AI automation is reduced substantially when the target systems are already Microsoft platforms and the agent builder requires no specialist AI expertise.',
      'The release accelerates the convergence of productivity software and automation infrastructure. Businesses that delay building AI automation competency will find themselves further behind as these capabilities become standard features of enterprise software suites rather than specialist implementations.',
    ],
    source: 'Microsoft Tech Community',
    sourceUrl: 'https://techcommunity.microsoft.com',
    readTime: '4 min read',
    featured: false,
  },
  {
    slug: 'snowflake-arctic-embed-enterprise-rag',
    category: 'Data Engineering',
    headline: 'Snowflake Launches Arctic Embed 2.0 to Power Enterprise RAG Pipelines Natively',
    summary: 'Snowflake\'s new embedding model integrates directly into Cortex AI, enabling retrieval-augmented generation without data leaving the data warehouse.',
    body: [
      'Snowflake has released Arctic Embed 2.0, a new state-of-the-art embedding model integrated natively into its Cortex AI platform, enabling organisations to build retrieval-augmented generation pipelines directly inside Snowflake without extracting data to external vector stores.',
      'The announcement addresses one of the most significant friction points in enterprise RAG adoption: the requirement to move sensitive business data out of governed data warehouses into external vector databases such as Pinecone or Weaviate. With Arctic Embed running inside Snowflake, embeddings are generated, stored, and queried within the existing data perimeter, preserving compliance posture and governance controls.',
      'Arctic Embed 2.0 achieves performance benchmarks on par with leading third-party embedding models across standard retrieval evaluation datasets, while offering the operational advantage of native Cortex integration. Developers can embed documents, query for semantic similarity, and retrieve context for LLM prompts using standard SQL through the Snowflake interface their data teams already use.',
      'For enterprises running analytical workloads on Snowflake that also want to build AI-powered knowledge retrieval or document Q&A systems, this removes a major architectural blocker. The common pattern of maintaining a separate vector store synced to Snowflake data — with its associated latency, cost, and synchronisation complexity — becomes unnecessary.',
      'The broader signal is that enterprise data platforms are converging with AI infrastructure. Organisations that have built strong data foundations in cloud warehouses are increasingly well-positioned to layer AI capabilities on top without additional complexity, provided their platform of choice is making these integrations available natively.',
    ],
    source: 'Snowflake Blog',
    sourceUrl: 'https://www.snowflake.com/blog',
    readTime: '5 min read',
    featured: false,
  },
  {
    slug: 'n8n-ai-agent-nodes-v1',
    category: 'CRM & Workflows',
    headline: 'n8n Releases AI Agent Nodes v1.0, Making LLM-Powered Automation Accessible to All Teams',
    summary: 'n8n\'s new AI Agent nodes allow non-technical teams to build autonomous, multi-tool AI workflows without writing code, using a visual drag-and-drop interface.',
    body: [
      'n8n, the open-source workflow automation platform, has released AI Agent Nodes v1.0, a major update that brings autonomous LLM-powered agents into its visual workflow builder. The release makes it possible for non-technical teams to construct AI agents that can use multiple tools, reason about inputs, and make decisions within automated workflows — all without writing code.',
      'The AI Agent node connects to any LLM provider including OpenAI, Anthropic, and locally hosted models, and can be given a set of tools — HTTP requests, database lookups, CRM reads and writes, email sends — that the agent selects and uses autonomously to complete a given objective. The agent reasons through the task, choosing the right sequence of tool calls to achieve the result.',
      'Practical examples from the n8n community include: customer support agents that look up order history, check policies, and draft resolution emails autonomously; lead enrichment workflows that research contacts across multiple sources and update CRM records; and operations bots that monitor data feeds and trigger appropriate actions based on conditions they evaluate in real time.',
      'The v1.0 release brings production-grade reliability to the agent nodes, including improved error handling, retry logic, memory persistence between workflow runs, and detailed execution logs for debugging. These features address the main concerns that previously made AI agent workflows unsuitable for business-critical automation.',
      'For automation practitioners evaluating how to integrate AI into existing n8n workflows, the agent node represents a step change in capability. Rather than engineering explicit logic paths for every possible scenario, workflows can now delegate open-ended tasks to an agent, making automation more resilient to variation and reducing the ongoing maintenance burden of rigid rule-based flows.',
    ],
    source: 'n8n Blog',
    sourceUrl: 'https://n8n.io/blog',
    readTime: '4 min read',
    featured: false,
  },
  {
    slug: 'openai-enterprise-api-batch-processing',
    category: 'AI & Machine Learning',
    headline: 'OpenAI Expands Enterprise API with Batch Processing and Lower Latency Tiers',
    summary: 'New pricing tiers and async batch endpoints make large-scale AI workloads significantly more cost-effective for enterprise deployments.',
    body: [
      'OpenAI has announced a significant expansion of its enterprise API offering, introducing asynchronous batch processing endpoints and tiered latency options that dramatically reduce the cost of running large-scale AI workloads in production.',
      'The new batch API allows enterprise customers to submit large volumes of requests at up to 50% lower cost compared to synchronous calls, with results returned within 24 hours. This makes use cases such as bulk document classification, data enrichment pipelines, and overnight report generation substantially more economical.',
      'The tiered latency system gives developers explicit control over response speed versus cost, with a "standard" tier optimised for throughput and a "realtime" tier retaining the low-latency behaviour existing API customers depend on.',
      'For businesses already running AI-powered automation workflows, these changes represent a meaningful shift. Workloads that previously required careful cost management can now be scaled more aggressively, and new use cases that were previously cost-prohibitive — such as enriching entire CRM databases with AI-generated summaries — become commercially viable.',
      'The announcement reinforces the broader trend of AI infrastructure becoming a commodity utility: powerful, accessible, and increasingly cheap at scale. Organisations that have already built automation foundations will be best placed to capitalise on these reduced costs.',
    ],
    source: 'The Verge',
    sourceUrl: 'https://www.theverge.com/ai-artificial-intelligence',
    readTime: '3 min read',
    featured: true,
  },
  {
    slug: 'gartner-intelligent-automation-2026',
    category: 'Business Automation',
    headline: 'Gartner: 80% of Organisations Will Use Intelligent Automation by 2026',
    summary: 'A new Gartner report projects rapid automation adoption across finance, HR, and supply chain with ROI realised in under 12 months for most deployments.',
    body: [
      'Gartner\'s latest Automation Adoption Forecast projects that 80% of enterprise organisations will have deployed some form of intelligent automation by 2026, up from an estimated 52% today. The report defines intelligent automation as the combination of robotic process automation (RPA), AI-driven decision engines, and workflow orchestration platforms.',
      'Finance, HR operations, and supply chain management are identified as the three highest-adoption verticals, with process automation delivering median cost reductions of 22 to 35% in repetitive back-office functions.',
      'Critically, the report finds that organisations achieving positive ROI within 12 months share several common characteristics: they began with a structured process discovery audit, they automated high-frequency tasks first, and they integrated automation into existing systems rather than replacing them.',
      'The forecast also warns against what Gartner terms "automation debt" — the accumulation of fragile, undocumented automations built without governance frameworks. Organisations that automate without clear ownership and monitoring structures are found to incur remediation costs that frequently exceed the original savings.',
      'For leadership teams still early in their automation journey, the report recommends starting with a formal process audit to identify the highest-ROI candidates before committing to any technology platform. The choice of tooling, Gartner emphasises, should follow the process design — not precede it.',
    ],
    source: 'Gartner Research',
    sourceUrl: 'https://www.gartner.com/en/information-technology/insights/automation',
    readTime: '4 min read',
    featured: false,
  },
  {
    slug: 'dbt-core-1-8-incremental-strategies',
    category: 'Data Engineering',
    headline: 'dbt Labs Releases dbt Core 1.8 with Significantly Improved Incremental Strategies',
    summary: 'The latest release introduces microbatch incremental materialisation, reducing full-refresh costs for large analytical pipelines.',
    body: [
      'dbt Labs has released dbt Core 1.8, introducing a new microbatch incremental materialisation strategy that addresses one of the most common pain points in large-scale analytical pipelines: the cost and time of processing only new or changed records without triggering expensive full-refresh operations.',
      'The microbatch strategy allows engineers to define a time-based partition boundary, processing only the records that fall within the most recent batch window. This is particularly valuable for event-driven data pipelines where source data arrives continuously and daily full refreshes are operationally prohibitive.',
      'The release also includes improved support for the dbt unit testing framework introduced in 1.7, with better handling of edge cases and expanded compatibility across warehouse adapters including BigQuery, Snowflake, Databricks, and Redshift.',
      'For data engineering teams managing high-volume pipelines, the practical impact is significant. Pipelines that previously required overnight full refreshes to maintain accuracy can now be restructured as incremental microbatch jobs, reducing warehouse compute costs and enabling fresher data for downstream BI and analytics consumers.',
      'The release reflects the broader maturation of the modern data stack: tooling is becoming more sophisticated, and the gap between raw capability and production-ready robustness continues to close.',
    ],
    source: 'dbt Blog',
    sourceUrl: 'https://www.getdbt.com/blog',
    readTime: '5 min read',
    featured: false,
  },
  {
    slug: 'hubspot-breeze-ai-crm-copilot',
    category: 'CRM & Workflows',
    headline: 'HubSpot Launches AI-Powered CRM Copilot Across All Professional Tiers',
    summary: 'HubSpot Breeze AI now automates contact enrichment, deal scoring, and email sequencing natively inside its CRM platform.',
    body: [
      'HubSpot has rolled out Breeze AI, its integrated AI copilot, to all Professional and Enterprise tier subscribers — making AI-powered CRM features accessible to a significantly wider range of businesses than before.',
      'Breeze AI covers three core automation areas: contact and company enrichment, which automatically fills missing firmographic data from public sources; predictive deal scoring, which surfaces the leads most likely to convert based on historical patterns; and AI-generated email sequences, which drafts personalised outreach based on a contact\'s engagement history and profile.',
      'The integration is native, meaning no additional tools or API connections are required. Sales and marketing teams can access Breeze features directly within the HubSpot interface they already use, reducing the friction that typically accompanies AI tool adoption.',
      'For revenue operations teams, the announcement has practical implications for how CRM hygiene and lead management are handled. Tasks that previously required manual data entry, external enrichment tools, or dedicated RevOps analysts can now be partially automated within the existing platform stack.',
      'HubSpot\'s move reflects a broader shift among CRM providers toward embedding AI natively rather than offering it as a bolt-on product. Businesses evaluating CRM platforms in 2025 should expect AI-assisted workflows to become a standard capability rather than a premium differentiator.',
    ],
    source: 'TechCrunch',
    sourceUrl: 'https://techcrunch.com/tag/hubspot/',
    readTime: '3 min read',
    featured: false,
  },
  {
    slug: 'mckinsey-automated-reporting-decision-latency',
    category: 'Digital Transformation',
    headline: 'McKinsey: Firms That Automate Reporting Cycles Cut Decision Latency by 60%',
    summary: 'A global study finds that executive teams with automated analytics pipelines make strategic decisions three times faster than peers using manual reporting.',
    body: [
      'A new McKinsey Global Institute study examining 400 mid-to-large enterprises across 14 countries has found that organisations with fully automated management reporting cycles make strategic decisions 60% faster than those relying on manual data collection and consolidation.',
      'The study defines "automated reporting" as the full pipeline from data source to executive dashboard without manual intervention: automated extraction, transformation, validation, and visualisation. Organisations that achieve this end-to-end automation report median decision latency of 2.3 days versus 5.8 days for those with manual steps in the process.',
      'Beyond speed, the research identifies quality improvements as a significant secondary benefit. Automated pipelines produce fewer errors, enable more consistent metric definitions across business units, and give leadership teams greater confidence in the numbers they are acting on.',
      'The study also examines what distinguishes organisations that successfully automate reporting from those that attempt it and fail. The most common failure mode is building dashboards before establishing a reliable, governed data foundation — producing visualisations that look impressive but are fed by inconsistent or poorly defined source data.',
      'For finance, operations, and strategy leaders, the practical takeaway is clear: the investment in data infrastructure and pipeline automation is not a technology project. It is an operational capability that directly affects the speed and quality of the decisions that drive the business forward.',
    ],
    source: 'McKinsey & Co.',
    sourceUrl: 'https://www.mckinsey.com/capabilities/mckinsey-digital/our-insights',
    readTime: '6 min read',
    featured: false,
  },
  {
    slug: 'aws-eventbridge-workflow-orchestration',
    category: 'Cloud & Infrastructure',
    headline: 'AWS Announces Native Workflow Orchestration for Data Pipelines in All Regions',
    summary: 'Amazon EventBridge Pipes now supports complex multi-step data pipeline orchestration, reducing reliance on third-party tools for ETL workflows.',
    body: [
      'Amazon Web Services has announced a significant expansion of EventBridge Pipes, its event-driven integration service, to support multi-step workflow orchestration for data pipelines across all AWS commercial regions.',
      'The update introduces conditional branching, error handling with retry logic, and parallel execution paths directly within EventBridge Pipes — capabilities previously requiring AWS Step Functions or third-party orchestration tools such as Apache Airflow or Prefect.',
      'For engineering teams building data pipelines on AWS, the practical impact is a consolidation of tooling. ETL workflows that previously required Step Functions for orchestration, Lambda for transformation, and EventBridge for triggering can now be defined as a single Pipes pipeline with native support for all three concerns.',
      'The announcement is particularly relevant for organisations running event-driven architectures where real-time data from SaaS applications, databases, and IoT sources needs to be processed, transformed, and routed without manual intervention. Native orchestration support reduces both the operational overhead and the latency introduced by multi-service pipeline designs.',
      'As cloud providers continue to expand their native integration capabilities, the cost-benefit calculation for third-party iPaaS tools shifts. Engineering teams evaluating their data pipeline architecture in 2025 should factor in the growing breadth of what is now available natively on major cloud platforms before committing to external orchestration services.',
    ],
    source: 'AWS Blog',
    sourceUrl: 'https://aws.amazon.com/blogs/aws/',
    readTime: '4 min read',
    featured: false,
  },
]

export function getNewsBySlug(slug: string): NewsItem | undefined {
  return news.find(n => n.slug === slug)
}
