export interface SearchEntry {
  id: string
  title: string
  section: string
  href: string
  category: string
  content: string
  breadcrumb: string
}

const INDEX: SearchEntry[] = [
  // ─── Home page sections ────────────────────────────────────────────────────
  {
    id: 'home-hero',
    title: 'Home',
    section: 'Hero',
    href: '/',
    category: 'Page',
    breadcrumb: 'Home',
    content: 'Sync4Tech AI automation digital transformation mid-market businesses enterprise-grade results ROI measurable outcomes building automation data AI agents',
  },
  {
    id: 'home-transformation-os',
    title: 'The Transformation Operating System',
    section: 'What We Build',
    href: '/#solutions',
    category: 'Platform',
    breadcrumb: 'Home › What We Build',
    content: 'AI Enablement Intelligence Layer Deploy purpose-built AI agents copilots decision engines trained on your business context. Custom LLM fine-tuning AI workflow orchestration predictive analytics. Business Automation Execution Layer End-to-end process automation eliminates manual work across every business function. RPA intelligent automation cross-system orchestration human-in-the-loop design. Data Transformation modern data infrastructure fragmented data real-time strategic intelligence data lakehouse architecture real-time pipelines self-serve analytics. Execution Excellence change management adoption programs transformation sticks digital adoption programs KPI frameworks continuous improvement.',
  },
  {
    id: 'home-execution-gap',
    title: 'Close Your Execution Gap',
    section: 'Execution Gap',
    href: '/',
    category: 'Page',
    breadcrumb: 'Home › Execution Gap',
    content: '12 weeks average time to measurable ROI 80% routine tasks eliminated on day one 3x faster team output post-implementation free strategy session no commitment required costing you growth every quarter',
  },
  {
    id: 'home-why-us',
    title: 'The Sync4Tech Difference',
    section: 'Why Us',
    href: '/',
    category: 'Page',
    breadcrumb: 'Home › Why Us',
    content: 'Traditional consultancies sell time we sell outcomes. Delivery speed weeks not months versus multi-quarter engagements. Technology best-of-breed stack vendor-agnostic versus tied to proprietary tools. Team structure embedded specialists versus rotating junior consultants. Outcomes focus ROI-guaranteed milestones versus effort-based billing. AI capability native AI-first delivery versus AI bolted on to old methods. Transparency weekly demos live dashboards versus monthly status reports.',
  },
  {
    id: 'home-faq',
    title: 'Frequently Asked Questions',
    section: 'FAQ',
    href: '/#faq',
    category: 'FAQ',
    breadcrumb: 'Home › FAQ',
    content: 'manual reporting automated dashboards data sources CRM ERP single view sales leads follow-ups CRM automation compliance reporting quarterly automation scale without hiring onboarding slow inconsistent business data decisions finance reconciliation invoice processing digital transformation stalled which processes to automate AI value versus hype technology strategy change management adoption engagement process why Sync4Tech versus large consultancy senior practitioners ROI 12 weeks',
  },

  // ─── Services overview ─────────────────────────────────────────────────────
  {
    id: 'services',
    title: 'Services',
    section: 'Overview',
    href: '/services',
    category: 'Services',
    breadcrumb: 'Services',
    content: 'Data Intelligence Suite Business Process Automation Consulting Strategy AI enablement workflow automation CRM ERP analytics reporting data engineering managed services digital transformation',
  },

  // ─── Data Intelligence ─────────────────────────────────────────────────────
  {
    id: 'services-data-intelligence',
    title: 'Data Intelligence Suite',
    section: 'Service Overview',
    href: '/services/data-intelligence',
    category: 'Data Intelligence',
    breadcrumb: 'Services › Data Intelligence',
    content: 'Data Intelligence Suite modern data infrastructure fragmented data real-time strategic intelligence business decisions analytics reporting data science AI machine learning',
  },
  {
    id: 'data-engineering',
    title: 'Data Engineering',
    section: 'Service',
    href: '/services/data-intelligence/data-engineering',
    category: 'Data Intelligence',
    breadcrumb: 'Services › Data Intelligence › Data Engineering',
    content: 'Data Engineering build reliable scalable data pipelines ETL ELT ingestion transformation loading data infrastructure cloud AWS Azure GCP spark databricks dbt batch streaming real-time pipelines data quality governance fragmented data sources unified single source of truth automated pipelines reduce manual data work engineering team throughput',
  },
  {
    id: 'data-management',
    title: 'Data Management',
    section: 'Service',
    href: '/services/data-intelligence/data-management',
    category: 'Data Intelligence',
    breadcrumb: 'Services › Data Intelligence › Data Management',
    content: 'Data Management data quality governance master data management MDM data catalog lineage metadata management data lake warehouse lakehouse data ops GDPR compliance data policies stewardship ownership messy unclean inconsistent data siloed spreadsheets',
  },
  {
    id: 'business-intelligence',
    title: 'Business Intelligence',
    section: 'Service',
    href: '/services/data-intelligence/business-intelligence',
    category: 'Data Intelligence',
    breadcrumb: 'Services › Data Intelligence › Business Intelligence',
    content: 'Business Intelligence BI dashboards reports KPIs metrics executive reporting Power BI Tableau Looker self-serve analytics operational dashboards real-time visibility manual reporting weekly reporting automated dashboards live data leadership team decisions revenue ops customer data',
  },
  {
    id: 'analytics-reporting',
    title: 'Analytics & Reporting',
    section: 'Service',
    href: '/services/data-intelligence/analytics-reporting',
    category: 'Data Intelligence',
    breadcrumb: 'Services › Data Intelligence › Analytics & Reporting',
    content: 'Analytics Reporting automated reporting data analysis operational analytics financial reporting compliance reporting audit trails monthly quarterly board reporting reduce reporting time save hours analysts automated collection transformation formatting',
  },
  {
    id: 'data-science-ai',
    title: 'Data Science & AI',
    section: 'Service',
    href: '/services/data-intelligence/data-science-ai',
    category: 'Data Intelligence',
    breadcrumb: 'Services › Data Intelligence › Data Science & AI',
    content: 'Data Science AI machine learning models predictive analytics forecasting demand planning anomaly detection customer churn prediction NLP natural language processing computer vision LLM large language models GPT fine-tuning AI agents copilots intelligent automation model training deployment MLOps',
  },
  {
    id: 'etl-pipelines',
    title: 'ETL Pipelines',
    section: 'Service',
    href: '/services/data-intelligence/etl-pipelines',
    category: 'Data Intelligence',
    breadcrumb: 'Services › Data Intelligence › ETL Pipelines',
    content: 'ETL ELT pipelines extract transform load data movement integration Airflow Prefect Dagster dbt Fivetran Stitch cloud data warehouse automated data ingestion batch streaming real-time API integrations connectors database migration',
  },
  {
    id: 'data-warehousing',
    title: 'Data Warehousing',
    section: 'Service',
    href: '/services/data-intelligence/data-warehousing',
    category: 'Data Intelligence',
    breadcrumb: 'Services › Data Intelligence › Data Warehousing',
    content: 'Data Warehousing Snowflake BigQuery Redshift data warehouse cloud lakehouse architecture centralised data storage schema design data modelling star schema dimensional modelling operational data store single source truth unified reporting',
  },
  {
    id: 'predictive-analytics',
    title: 'Predictive Analytics',
    section: 'Service',
    href: '/services/data-intelligence/predictive-analytics',
    category: 'Data Intelligence',
    breadcrumb: 'Services › Data Intelligence › Predictive Analytics',
    content: 'Predictive Analytics forecasting demand planning churn prediction sales forecasting inventory optimisation revenue prediction anomaly detection machine learning statistical models time series regression classification',
  },

  // ─── Automation ────────────────────────────────────────────────────────────
  {
    id: 'services-automation',
    title: 'Business Process Automation',
    section: 'Service Overview',
    href: '/services/automation',
    category: 'Automation',
    breadcrumb: 'Services › Automation',
    content: 'Business Process Automation end-to-end process automation eliminates manual work workflows RPA intelligent automation eliminate repetitive tasks scale headcount efficiency operational excellence',
  },
  {
    id: 'workflow-automation',
    title: 'Workflow Automation',
    section: 'Service',
    href: '/services/automation/workflow-automation',
    category: 'Automation',
    breadcrumb: 'Services › Automation › Workflow Automation',
    content: 'Workflow Automation automate business processes end-to-end approval workflows notification triggers escalation rules task routing document collection handoff automated steps reduce manual effort eliminate repetitive work Zapier Make n8n Power Automate Microsoft low-code no-code process mapping human-in-the-loop',
  },
  {
    id: 'crm-automation',
    title: 'CRM Automation',
    section: 'Service',
    href: '/services/automation/crm-automation',
    category: 'Automation',
    breadcrumb: 'Services › Automation › CRM Automation',
    content: 'CRM Automation Salesforce HubSpot Pipedrive lead management sales pipeline follow-up sequences auto-assign leads escalation triggers no lead goes cold 30-50% improvement lead conversion rates contact management deal stages automated outreach sequences email automation sales velocity pipeline visibility reporting',
  },
  {
    id: 'sales-automation',
    title: 'Sales Automation',
    section: 'Service',
    href: '/services/automation/sales-automation',
    category: 'Automation',
    breadcrumb: 'Services › Automation › Sales Automation',
    content: 'Sales Automation prospect outreach sequences lead scoring qualification automated proposals quote generation contract sending follow-up reminders pipeline reporting revenue forecasting sales team productivity SDR AE automation reduce manual admin',
  },
  {
    id: 'marketing-automation',
    title: 'Marketing Automation',
    section: 'Service',
    href: '/services/automation/marketing-automation',
    category: 'Automation',
    breadcrumb: 'Services › Automation › Marketing Automation',
    content: 'Marketing Automation email campaigns drip nurture sequences segmentation personalisation lead scoring attribution reporting campaign management HubSpot Marketo Mailchimp ActiveCampaign customer journey mapping re-engagement win-back automated content',
  },
  {
    id: 'ai-automation',
    title: 'AI Automation',
    section: 'Service',
    href: '/services/automation/ai-automation',
    category: 'Automation',
    breadcrumb: 'Services › Automation › AI Automation',
    content: 'AI Automation artificial intelligence intelligent process automation AI agents copilots LLM GPT document processing intelligent document recognition NLP classification extraction autonomous agents decision making agentic workflows smart routing AI-powered workflows',
  },
  {
    id: 'erp-business-systems',
    title: 'ERP & Business Systems',
    section: 'Service',
    href: '/services/automation/erp-business-systems',
    category: 'Automation',
    breadcrumb: 'Services › Automation › ERP & Business Systems',
    content: 'ERP Business Systems SAP Oracle NetSuite Microsoft Dynamics integration automation system integrations API middleware data sync across systems finance HR supply chain procurement inventory order management ERP implementation customisation',
  },
  {
    id: 'internal-operations',
    title: 'Internal Operations',
    section: 'Service',
    href: '/services/automation/internal-operations',
    category: 'Automation',
    breadcrumb: 'Services › Automation › Internal Operations',
    content: 'Internal Operations automation HR onboarding IT provisioning approvals expense management facilities asset management employee request handling ticketing internal portals automated onboarding offboarding employee experience ops efficiency',
  },
  {
    id: 'document-automation',
    title: 'Document Automation',
    section: 'Service',
    href: '/services/automation/document-automation',
    category: 'Automation',
    breadcrumb: 'Services › Automation › Document Automation',
    content: 'Document Automation contract generation template population document assembly e-signature docusign PDF generation invoice automation proposal generation compliance documents automated document workflows OCR data extraction intelligent forms',
  },

  // ─── Consulting ────────────────────────────────────────────────────────────
  {
    id: 'services-consulting',
    title: 'Consulting & Strategy',
    section: 'Service Overview',
    href: '/services/consulting',
    category: 'Consulting',
    breadcrumb: 'Services › Consulting',
    content: 'Consulting Strategy digital transformation advisory technology roadmap strategic assessment senior practitioners board-ready strategy ROI model business outcomes change management',
  },
  {
    id: 'business-analysis',
    title: 'Business Analysis',
    section: 'Service',
    href: '/services/consulting/business-analysis',
    category: 'Consulting',
    breadcrumb: 'Services › Consulting › Business Analysis',
    content: 'Business Analysis process mapping requirements gathering as-is to-be analysis gap analysis stakeholder interviews process documentation current state future state operational efficiency identification pain points improvement opportunities business case ROI model automation readiness assessment',
  },
  {
    id: 'digital-transformation',
    title: 'Digital Transformation',
    section: 'Service',
    href: '/services/consulting/digital-transformation',
    category: 'Consulting',
    breadcrumb: 'Services › Consulting › Digital Transformation',
    content: 'Digital Transformation strategy roadmap technology modernisation legacy system replacement cloud migration AI readiness change management programme management stalled transformation initiative business outcomes measurable results 12-24 month roadmap board-ready strategy transformation partner',
  },
  {
    id: 'solution-architecture',
    title: 'Solution Architecture',
    section: 'Service',
    href: '/services/consulting/solution-architecture',
    category: 'Consulting',
    breadcrumb: 'Services › Consulting › Solution Architecture',
    content: 'Solution Architecture technical design system design cloud architecture AWS Azure GCP microservices API design integration architecture scalable secure maintainable enterprise architecture technology selection vendor evaluation',
  },
  {
    id: 'project-delivery',
    title: 'Project & Delivery Management',
    section: 'Service',
    href: '/services/consulting/project-delivery',
    category: 'Consulting',
    breadcrumb: 'Services › Consulting › Project & Delivery Management',
    content: 'Project Delivery Management programme management agile scrum sprints delivery oversight weekly demos milestones accountability on time on budget dedicated project manager risk management stakeholder communication',
  },
  {
    id: 'governance-compliance',
    title: 'Governance & Compliance',
    section: 'Service',
    href: '/services/consulting/governance-compliance',
    category: 'Consulting',
    breadcrumb: 'Services › Consulting › Governance & Compliance',
    content: 'Governance Compliance GDPR data protection regulatory compliance ISO audit readiness data governance framework policy development risk management compliance automation reporting audit trails data residency privacy',
  },
  {
    id: 'ai-readiness',
    title: 'AI Readiness Assessment',
    section: 'Service',
    href: '/services/consulting/ai-readiness',
    category: 'Consulting',
    breadcrumb: 'Services › Consulting › AI Readiness Assessment',
    content: 'AI Readiness Assessment evaluate your organisation for AI adoption data maturity model AI use cases that have proven ROI predictive demand forecasting intelligent document processing anomaly detection customer churn prediction evaluate AI hype versus value recommended use cases budget data readiness',
  },
  {
    id: 'automation-audit',
    title: 'Automation Audit',
    section: 'Service',
    href: '/services/consulting/automation-audit',
    category: 'Consulting',
    breadcrumb: 'Services › Consulting › Automation Audit',
    content: 'Automation Audit prioritisation framework score processes volume friction impact highest ROI automation first Phase 1 quick wins automation opportunities assessment existing systems bottlenecks inefficiencies current state review',
  },
  {
    id: 'fractional-cdo-cao',
    title: 'Fractional CDO / CAO',
    section: 'Service',
    href: '/services/consulting/fractional-cdo-cao',
    category: 'Consulting',
    breadcrumb: 'Services › Consulting › Fractional CDO / CAO',
    content: 'Fractional CDO CAO Chief Data Officer Chief Automation Officer senior leadership data strategy automation strategy without full-time hire part-time fractional executive data transformation programme sponsorship board reporting executive accountability technology roadmap ownership',
  },

  // ─── Industries ────────────────────────────────────────────────────────────
  {
    id: 'industries',
    title: 'Industries',
    section: 'Overview',
    href: '/industries',
    category: 'Industries',
    breadcrumb: 'Industries',
    content: 'Industries real estate healthcare manufacturing retail ecommerce logistics education financial services legal technology SaaS professional services hospitality travel non-profit public sector sector expertise domain knowledge',
  },
  {
    id: 'industry-real-estate',
    title: 'Real Estate',
    section: 'Industry',
    href: '/industries/real-estate',
    category: 'Industries',
    breadcrumb: 'Industries › Real Estate',
    content: 'Real Estate automation property management CRM tenant onboarding lease management document automation contract generation maintenance ticketing property data analytics portfolio reporting compliance reporting landlord tenant agent workflow automation listing management deal pipeline',
  },
  {
    id: 'industry-healthcare',
    title: 'Healthcare',
    section: 'Industry',
    href: '/industries/healthcare',
    category: 'Industries',
    breadcrumb: 'Industries › Healthcare',
    content: 'Healthcare automation patient onboarding appointment scheduling billing claims processing compliance HIPAA regulatory reporting clinical data analytics EHR EMR integration document automation prior authorisation care coordination operational efficiency hospital clinic medical practice',
  },
  {
    id: 'industry-manufacturing',
    title: 'Manufacturing',
    section: 'Industry',
    href: '/industries/manufacturing',
    category: 'Industries',
    breadcrumb: 'Industries › Manufacturing',
    content: 'Manufacturing automation supply chain inventory management production planning quality control ERP integration order management procurement automation predictive maintenance IoT data analytics OEE operational efficiency factory floor reporting',
  },
  {
    id: 'industry-retail-ecommerce',
    title: 'Retail & E-Commerce',
    section: 'Industry',
    href: '/industries/retail-ecommerce',
    category: 'Industries',
    breadcrumb: 'Industries › Retail & E-Commerce',
    content: 'Retail E-Commerce automation inventory management order management fulfilment customer service automation product catalogue CRM personalisation marketing automation returns refunds ecommerce platform Shopify WooCommerce customer data analytics demand forecasting',
  },
  {
    id: 'industry-logistics',
    title: 'Logistics',
    section: 'Industry',
    href: '/industries/logistics',
    category: 'Industries',
    breadcrumb: 'Industries › Logistics',
    content: 'Logistics automation route optimisation fleet management shipment tracking dispatch automation customer notifications POD proof of delivery freight billing invoice automation 3PL warehouse management supply chain visibility operational reporting',
  },
  {
    id: 'industry-education',
    title: 'Education',
    section: 'Industry',
    href: '/industries/education',
    category: 'Industries',
    breadcrumb: 'Industries › Education',
    content: 'Education automation student enrolment admissions onboarding LMS integration course management administrative automation compliance reporting attendance data analytics student experience staff operations',
  },
  {
    id: 'industry-financial-services',
    title: 'Financial Services',
    section: 'Industry',
    href: '/industries/financial-services',
    category: 'Industries',
    breadcrumb: 'Industries › Financial Services',
    content: 'Financial Services automation compliance reporting regulatory KYC AML onboarding reconciliation invoice processing accounts payable receivable financial reporting audit risk management fraud detection fintech banking insurance wealth management',
  },
  {
    id: 'industry-legal',
    title: 'Legal',
    section: 'Industry',
    href: '/industries/legal',
    category: 'Industries',
    breadcrumb: 'Industries › Legal',
    content: 'Legal automation contract management document generation e-signature matter management billing time tracking compliance client onboarding legal ops law firm efficiency document review due diligence regulatory reporting case management',
  },
  {
    id: 'industry-technology-saas',
    title: 'Technology & SaaS',
    section: 'Industry',
    href: '/industries/technology-saas',
    category: 'Industries',
    breadcrumb: 'Industries › Technology & SaaS',
    content: 'Technology SaaS automation customer onboarding product analytics data pipeline revenue operations RevOps customer success churn prediction usage analytics billing dunning sales automation CRM integration growth analytics PLG product-led growth',
  },
  {
    id: 'industry-professional-services',
    title: 'Professional Services',
    section: 'Industry',
    href: '/industries/professional-services',
    category: 'Industries',
    breadcrumb: 'Industries › Professional Services',
    content: 'Professional Services automation project management time tracking billing invoicing resource planning capacity utilisation client reporting CRM proposal generation consulting agency accounting firm operations efficiency',
  },
  {
    id: 'industry-hospitality-travel',
    title: 'Hospitality & Travel',
    section: 'Industry',
    href: '/industries/hospitality-travel',
    category: 'Industries',
    breadcrumb: 'Industries › Hospitality & Travel',
    content: 'Hospitality Travel automation guest experience booking management reservation systems CRM loyalty programmes revenue management pricing dynamic pricing hotel restaurant operations guest communications post-stay follow-up review management',
  },
  {
    id: 'industry-nonprofit-public-sector',
    title: 'Non-Profit & Public Sector',
    section: 'Industry',
    href: '/industries/nonprofit-public-sector',
    category: 'Industries',
    breadcrumb: 'Industries › Non-Profit & Public Sector',
    content: 'Non-Profit Public Sector automation grant management donor management fundraising CRM volunteer management compliance reporting impact reporting programme management government public services digital transformation',
  },

  // ─── Case Studies ──────────────────────────────────────────────────────────
  {
    id: 'case-studies',
    title: 'Case Studies',
    section: 'Overview',
    href: '/case-studies',
    category: 'Case Studies',
    breadcrumb: 'Case Studies',
    content: 'Case Studies client results ROI measurable outcomes automation data intelligence transformation healthcare logistics financial services legal real estate results 340% ROI time saved costs reduced errors eliminated revenue unlocked',
  },

  // ─── Insights ──────────────────────────────────────────────────────────────
  {
    id: 'insights',
    title: 'Insights',
    section: 'Overview',
    href: '/insights',
    category: 'Insights',
    breadcrumb: 'Insights',
    content: 'Insights blog articles guides automation AI data intelligence digital transformation thought leadership best practices how-to tutorials industry trends',
  },

  // ─── Pricing ───────────────────────────────────────────────────────────────
  {
    id: 'pricing',
    title: 'Pricing',
    section: 'Overview',
    href: '/pricing',
    category: 'Page',
    breadcrumb: 'Pricing',
    content: 'Pricing transparent outcome-based no hidden fees no bloated retainers fixed-price projects Starter Quick Win Automation from £5000 2-4 week delivery Growth Full Automation Programme from £15000 6-12 weeks Enterprise Transformation Partnership custom pricing ongoing engagement free strategy session NDA available global delivery',
  },
  {
    id: 'pricing-starter',
    title: 'Starter — Quick Win Automation',
    section: 'Pricing Tier',
    href: '/pricing',
    category: 'Pricing',
    breadcrumb: 'Pricing › Starter',
    content: 'Starter Quick Win Automation from £5000 project 2-4 week delivery up to 3 automated workflows 1 system integration basic reporting dashboard dedicated project manager post-launch documentation 2 weeks support small teams testing automation first time',
  },
  {
    id: 'pricing-growth',
    title: 'Growth — Full Automation Programme',
    section: 'Pricing Tier',
    href: '/pricing',
    category: 'Pricing',
    breadcrumb: 'Pricing › Growth',
    content: 'Growth Full Automation Programme from £15000 project 6-12 week delivery end-to-end automation design unlimited workflows full system integrations ROI tracking dashboard 3 months post-launch support weekly progress demos dedicated project manager scaling mid-market businesses',
  },
  {
    id: 'pricing-enterprise',
    title: 'Enterprise — Transformation Partnership',
    section: 'Pricing Tier',
    href: '/pricing',
    category: 'Pricing',
    breadcrumb: 'Pricing › Enterprise',
    content: 'Enterprise Transformation Partnership custom pricing ongoing engagement dedicated specialist team custom AI development data infrastructure design change management support quarterly business reviews priority support SLA NDA included multi-geography delivery long-term transformation partner',
  },

  // ─── About ─────────────────────────────────────────────────────────────────
  {
    id: 'about',
    title: 'About Sync4Tech',
    section: 'Overview',
    href: '/about',
    category: 'About',
    breadcrumb: 'About',
    content: 'About Sync4Tech global AI automation consultancy mid-market businesses 50-2000 employees enterprise-grade accessible team offices London New York Lahore 50 client organisations 340% average ROI three continents',
  },
  {
    id: 'about-mission',
    title: 'Our Mission',
    section: 'Mission',
    href: '/about/mission',
    category: 'About',
    breadcrumb: 'About › Mission',
    content: 'Mission make enterprise-grade AI automation genuinely accessible companies drive real economy mid-market businesses worldwide. Technology without adoption is waste. ROI is not optional it is the product. Global teams build better solutions. Founded 2021 First 10 clients healthcare legal financial services Asia Hub US Expansion 50 organisations 340% ROI TransformationOS methodology 2026',
  },
  {
    id: 'about-team',
    title: 'Our Team',
    section: 'Team',
    href: '/about/team',
    category: 'About',
    breadcrumb: 'About › Team',
    content: 'Team globally distributed remote-first culture senior practitioners embedded specialists cross-cultural teams three continents London New York Lahore leadership experienced consultants data engineers AI specialists project managers',
  },
  {
    id: 'about-partners',
    title: 'Partners',
    section: 'Partners',
    href: '/about/partners',
    category: 'About',
    breadcrumb: 'About › Partners',
    content: 'Partners technology partners Microsoft Azure AWS Google Cloud Salesforce HubSpot partner ecosystem regulated industries globally certified partnerships',
  },

  // ─── Careers ───────────────────────────────────────────────────────────────
  {
    id: 'careers',
    title: 'Careers',
    section: 'Overview',
    href: '/careers',
    category: 'Page',
    breadcrumb: 'Careers',
    content: 'Careers jobs hiring remote global data engineer AI engineer automation consultant project manager business analyst solution architect fractional CDO CAO join team remote global mid-market transformation',
  },

  // ─── Contact ───────────────────────────────────────────────────────────────
  {
    id: 'contact',
    title: 'Contact',
    section: 'Get In Touch',
    href: '/contact',
    category: 'Page',
    breadcrumb: 'Contact',
    content: 'Contact get in touch start transformation tell us biggest operational challenge strategy session book consultation hello@sync4tech.co response within 24 hours London New York Lahore offices free strategy session no commitment',
  },

  // ─── FAQ entries ───────────────────────────────────────────────────────────
  {
    id: 'faq-reporting',
    title: 'Manual reporting automation',
    section: 'FAQ',
    href: '/#faq',
    category: 'FAQ',
    breadcrumb: 'Home › FAQ',
    content: 'teams spend half week manual reporting fixed connect data sources automate collection transformation live dashboards reporting instant 10-15 hours reclaimed per analyst per week',
  },
  {
    id: 'faq-data-single-view',
    title: 'Single view of business data',
    section: 'FAQ',
    href: '/#faq',
    category: 'FAQ',
    breadcrumb: 'Home › FAQ',
    content: 'data everywhere spreadsheets CRMs ERPs single view unified data layer normalizing single source truth revenue ops customer data real time data fragmentation problem',
  },
  {
    id: 'faq-sales-leads',
    title: 'Sales lead follow-up automation',
    section: 'FAQ',
    href: '/#faq',
    category: 'FAQ',
    breadcrumb: 'Home › FAQ',
    content: 'sales team losing leads follow-ups slip through cracks CRM automation no lead goes cold intelligent follow-up sequences auto-assign escalation triggers 30-50% improvement lead conversion rates',
  },
  {
    id: 'faq-compliance',
    title: 'Compliance reporting automation',
    section: 'FAQ',
    href: '/#faq',
    category: 'FAQ',
    breadcrumb: 'Home › FAQ',
    content: 'compliance reporting takes weeks every quarter faster automate data collection validation formatting business rules 3 weeks run in hours full audit trails fewer human errors',
  },
  {
    id: 'faq-scale',
    title: 'Scale operations without hiring',
    section: 'FAQ',
    href: '/#faq',
    category: 'FAQ',
    breadcrumb: 'Home › FAQ',
    content: 'growing fast operations cannot keep up scale without hiring more people automation scale work without scaling headcount highest-volume repetitive processes onboarding invoicing order management data entry 3x throughput',
  },
  {
    id: 'faq-onboarding',
    title: 'Customer onboarding automation',
    section: 'FAQ',
    href: '/#faq',
    category: 'FAQ',
    breadcrumb: 'Home › FAQ',
    content: 'customer onboarding slow inconsistent automated map onboarding journey document collection verification triggers welcome communications account setup handoff notifications consistent faster experience',
  },
  {
    id: 'faq-finance',
    title: 'Finance reconciliation automation',
    section: 'FAQ',
    href: '/#faq',
    category: 'FAQ',
    breadcrumb: 'Home › FAQ',
    content: 'finance team buried reconciliation invoice processing automated invoice capture three-way matching payment scheduling exception flagging 70-80% less time transactional work analysis planning',
  },
  {
    id: 'faq-transformation-stalled',
    title: 'Digital transformation stalled',
    section: 'FAQ',
    href: '/#faq',
    category: 'FAQ',
    breadcrumb: 'Home › FAQ',
    content: 'digital transformation initiative stalled three reasons lack clear problem statement focus technology not business outcomes no one owning adoption strategic partner diagnosing root cause rebuilding roadmap measurable outcomes',
  },
  {
    id: 'faq-which-automate-first',
    title: 'Which processes to automate first',
    section: 'FAQ',
    href: '/#faq',
    category: 'FAQ',
    breadcrumb: 'Home › FAQ',
    content: 'automation prioritisation framework score processes three axes volume friction impact highest scoring processes Phase 1 first automation delivers ROI fast building momentum executive confidence',
  },
  {
    id: 'faq-ai-value',
    title: 'Where AI adds real value',
    section: 'FAQ',
    href: '/#faq',
    category: 'FAQ',
    breadcrumb: 'Home › FAQ',
    content: 'evaluating AI real value versus hype senior advisory predictive demand forecasting intelligent document processing anomaly detection customer churn prediction data maturity use case budget AI proven ROI',
  },
  {
    id: 'faq-technology-strategy',
    title: 'Technology strategy not just implementation',
    section: 'FAQ',
    href: '/#faq',
    category: 'FAQ',
    breadcrumb: 'Home › FAQ',
    content: 'technology strategy not just implementation Strategic Assessment current state highest-value opportunities automation data AI prioritised 12-24 month technology roadmap board-ready strategy before single line code written',
  },
  {
    id: 'faq-adoption',
    title: 'Change management and adoption',
    section: 'FAQ',
    href: '/#faq',
    category: 'FAQ',
    breadcrumb: 'Home › FAQ',
    content: 'team actually adopts new systems change management built every engagement involve team design day one training tailored each role structured adoption programme tracks usage addresses resistance',
  },
  {
    id: 'faq-engagement-process',
    title: 'Typical engagement process',
    section: 'FAQ',
    href: '/#faq',
    category: 'FAQ',
    breadcrumb: 'Home › FAQ',
    content: 'typical engagement four phases Discovery understanding business processes goals Strategy roadmap solution design success metrics Build automation data AI implementation sprints Optimise performance monitoring iteration improvement measurable ROI 12 weeks',
  },
  {
    id: 'faq-why-sync4tech',
    title: 'Why Sync4Tech vs large consultancy',
    section: 'FAQ',
    href: '/#faq',
    category: 'FAQ',
    breadcrumb: 'Home › FAQ',
    content: 'why Sync4Tech large consultancies sell strategy hand off implementation junior teams specialist firm senior practitioners working systems not reports accountable outcomes not hours results in weeks not quarters',
  },
  // ─── Insights articles ────────────────────────────────────────────────────
  {
    id: 'insight-automate-business-processes',
    title: 'How to Automate Your Business Processes',
    section: 'Insights',
    href: '/insights/how-to-automate-business-processes',
    category: 'Insights',
    breadcrumb: 'Insights › Automation',
    content: 'business process automation BPA automate workflows eliminate manual work increase efficiency reduce costs ROI which processes to automate first repetitive tasks data entry approvals notifications CRM ERP integration how long does automation take how much does it cost SMB small business automation ROI payback period AI automation vs BPA RPA robotic process automation step by step guide',
  },
  {
    id: 'insight-what-is-ai-automation',
    title: 'What Is AI Automation? A Plain-English Explainer',
    section: 'Insights',
    href: '/insights/what-is-ai-automation',
    category: 'Insights',
    breadcrumb: 'Insights › AI',
    content: 'what is AI automation artificial intelligence machine learning how does AI automation work difference between AI automation and RPA robotic process automation which industries benefit from AI automation healthcare finance retail manufacturing logistics how much does AI automation cost how to get started with AI automation does AI automation replace workers jobs future of work AI tools platforms',
  },
  {
    id: 'insight-connect-crm-to-other-tools',
    title: 'How to Connect Your CRM to Other Business Tools',
    section: 'Insights',
    href: '/insights/how-to-connect-crm-to-other-tools',
    category: 'Insights',
    breadcrumb: 'Insights › Operations',
    content: 'CRM integration connect HubSpot Salesforce Pipedrive to other tools ERP email marketing accounting invoicing helpdesk Zapier Make native integrations API webhooks how to connect HubSpot to other tools how to connect Salesforce to other tools CRM integration cost how long does CRM integration take best CRM for small business what data to sync between CRM and other systems bidirectional sync data consistency',
  },
  {
    id: 'insight-data-driven-decision-making',
    title: 'Data-Driven Decision Making: A Practical Guide',
    section: 'Insights',
    href: '/insights/data-driven-decision-making-guide',
    category: 'Insights',
    breadcrumb: 'Insights › Data',
    content: 'data driven decision making DDDM business intelligence BI analytics how to build BI from scratch dashboards KPI metrics Power BI Tableau Looker data warehouse analytics platform how long to see results from business intelligence what is BI difference between analytics and BI how to get team to use data culture change data literacy data engineering data lakehouse real time analytics',
  },
  {
    id: 'insight-choose-automation-consultant',
    title: 'How to Choose an Automation Consultant',
    section: 'Insights',
    href: '/insights/how-to-choose-automation-consultant',
    category: 'Insights',
    breadcrumb: 'Insights › Transformation',
    content: 'how to choose automation consultant what to look for in automation consultant red flags 10 questions to ask automation consultant how much does an automation consultant cost consultant vs agency vs in-house automation team how long does it take to work with automation consultant digital transformation consultant process automation specialist RPA consultant AI consultant credentials certifications case studies ROI outcomes',
  },
]

export default INDEX
